heat_template_version: 2014-10-16

resources:
  parent_vn:
    type: OS::ContrailV2::VirtualNetwork
    properties:
      name: { get_param: parent_net_name }
      network_ipam_refs: [{ get_param: ipam }]
      route_target_list:
        {
          route_target_list_route_target: [{ get_param: parent_net_rt }],
        }
      network_ipam_refs_data:
        [{
          network_ipam_refs_data_ipam_subnets:
            [{
              network_ipam_refs_data_ipam_subnets_subnet:
                {
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix: { get_param: parent_net_cidr },
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix_len: { get_param: parent_net_mask },
                },
                network_ipam_refs_data_ipam_subnets_addr_from_start: 'true',
                network_ipam_refs_data_ipam_subnets_gateway: { get_param: parent_net_gw }
         }]
     }]

vm_1:
    type: OS::Nova::Server
    properties:
      name: { get_param: vm_name_1 }
      image: { get_param: image }
      flavor: { get_param: flavor }
      networks:
        - network: { get_resource: parent_vn }

#SUBINT 1
child_vn_1:
    type: OS::ContrailV2::VirtualNetwork
    properties:
      name: { get_param: child_net_name_1 }
      network_ipam_refs: [{ get_param: ipam }]
      route_target_list:
        {
          route_target_list_route_target: [{ get_param: child_net_rt_1 }],
        }
      network_ipam_refs_data:
        [{
          network_ipam_refs_data_ipam_subnets:
            [{
              network_ipam_refs_data_ipam_subnets_subnet:
                {
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix: { get_param: child_net_cidr_1 },
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix_len: { get_param: child_net_mask_1 },
                },
                network_ipam_refs_data_ipam_subnets_addr_from_start: 'true',
                network_ipam_refs_data_ipam_subnets_gateway: { get_param: child_net_gw_1 }
         }]
     }]

  vmi_1:
    type: OS::ContrailV2::VirtualMachineInterface
    properties:
      name: { get_param: vmi_name_1 }
      virtual_network_refs: [{ get_resource: child_vn_1 }]
      virtual_machine_interface_properties:
        {
          virtual_machine_interface_properties_sub_interface_vlan_tag: { get_param: child_vlan_1 },
        }
      virtual_machine_interface_mac_addresses:
        {
          virtual_machine_interface_mac_addresses_mac_address: [{ get_attr: [vm_1, addresses, get_param: parent_net_name, 0, "OS-EXT-IPS-MAC:mac_addr"] }],
        }
      virtual_machine_interface_refs: [{ get_attr: [vm_1, addresses, get_param: parent_net_name, 0, "port"] }]

  iip_1:
    type: OS::ContrailV2::InstanceIp
    depends_on: [ vmi_1 ]
    properties:
      virtual_network_refs: [{ get_resource: child_vn_1 }]
      virtual_machine_interface_refs: [{ get_resource: vmi_1 }]

