heat_template_version: 2015-04-30

parameters:
  ipam:
    type: string
  vmname2:
    type: string
  vmname3:
    type: string
  vmimage:
    type: string
  vmflavor:
    type: string
  vlan1:
    type: string
  vlan2:
    type: string
  mgmt-net:
    type: string

resources:
  parent_vn:
    type: OS::ContrailV2::VirtualNetwork
    properties:
      name: 'parent'
      network_ipam_refs: [{ get_param: ipam }]
      network_ipam_refs_data:
        [{
          network_ipam_refs_data_ipam_subnets:
            [{
              network_ipam_refs_data_ipam_subnets_subnet:
                {
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix: '1.1.1.0',
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix_len: '24',
                },
            }]
        }]

  vm_1:
    type: OS::Nova::Server
    properties:
      name: 'trunk_vm'
      image: 'vsrxD110'
      flavor: 'vsrx'
      user_data_format: RAW
      user_data:
         get_file: './trunk_vsrx.txt'
      networks:
        - network: { get_param: mgmt-net }
        - network: { get_resource: parent_vn }

#SUBINTERFACES

#SUBINT 1
  child_vn_1:
    type: OS::ContrailV2::VirtualNetwork
    properties:
      name: 'child1'
      network_ipam_refs: [{ get_param: ipam }]
      network_ipam_refs_data:
        [{
          network_ipam_refs_data_ipam_subnets:
            [{
              network_ipam_refs_data_ipam_subnets_subnet:
                {
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix: '172.30.100.0',
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix_len: '24',
                },
         }]
     }]

  vmi_1:
    type: OS::ContrailV2::VirtualMachineInterface
    properties:
      name: 'vmi_1'
      virtual_network_refs: [{ get_resource: child_vn_1 }]
      virtual_machine_interface_properties:
        {
          virtual_machine_interface_properties_sub_interface_vlan_tag: { get_param: vlan1 },
        }
      virtual_machine_interface_mac_addresses:
        {
          virtual_machine_interface_mac_addresses_mac_address: [{ get_attr: [vm_1, addresses, 'parent', 0, "OS-EXT-IPS-MAC:mac_addr"] }],
        }
      virtual_machine_interface_refs: [{ get_attr: [vm_1, addresses, 'parent', 0, "port"] }]

  iip_1:
    type: OS::ContrailV2::InstanceIp
    depends_on: [ vmi_1 ]
    properties:
      virtual_network_refs: [{ get_resource: child_vn_1 }]
      virtual_machine_interface_refs: [{ get_resource: vmi_1 }]

#SUBINT 2
  child_vn_2:
    type: OS::ContrailV2::VirtualNetwork
    properties:
      name: 'child2'
      network_ipam_refs: [{ get_param: ipam }]
      network_ipam_refs_data:
        [{
          network_ipam_refs_data_ipam_subnets:
            [{
              network_ipam_refs_data_ipam_subnets_subnet:
                {
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix: '172.30.200.0',
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix_len: '24',
                },
         }]
     }]

  vmi_2:
    type: OS::ContrailV2::VirtualMachineInterface
    properties:
      name: 'vmi_2'
      virtual_network_refs: [{ get_resource: child_vn_2 }]
      virtual_machine_interface_properties:
        {
          virtual_machine_interface_properties_sub_interface_vlan_tag: '200',
        }
      virtual_machine_interface_mac_addresses:
        {
          virtual_machine_interface_mac_addresses_mac_address: [{ get_attr: [vm_1, addresses, 'parent', 0, "OS-EXT-IPS-MAC:mac_addr"] }],
        }
      virtual_machine_interface_refs: [{ get_attr: [vm_1, addresses, 'parent', 0, "port"] }]

  iip_2:
    type: OS::ContrailV2::InstanceIp
    depends_on: [ vmi_2 ]
    properties:
      virtual_network_refs: [{ get_resource: child_vn_2 }]
      virtual_machine_interface_refs: [{ get_resource: vmi_2 }]

#VM2
  vmi2:
    type: OS::ContrailV2::VirtualMachineInterface
    properties:
      virtual_network_refs: [{ list_join: [':', { get_attr: [ child_vn_2, fq_name ] } ] }]

  iip_2a:
    type: OS::ContrailV2::InstanceIp
    depends_on: [ vmi2 , child_vn_2]
    properties:
      virtual_machine_interface_refs: [{ get_resource: vmi2 }]
      virtual_network_refs: [{ list_join: [':', { get_attr: [ child_vn_2, fq_name ] } ] }]

  vm2: 
    type: OS::Nova::Server 
    depends_on: [iip_2a ]
    properties: 
      name: { get_param: vmname2 } 
      image: { get_param: vmimage } 
      flavor: { get_param: vmflavor } 
      networks: 
        - port: { get_resource: vmi2 } 

#VM3
  vmi3:
    type: OS::ContrailV2::VirtualMachineInterface
    properties:
      virtual_network_refs: [{ list_join: [':', { get_attr: [ child_vn_1, fq_name ] } ] }]

  iip_3:
    type: OS::ContrailV2::InstanceIp
    depends_on: [ vmi3, child_vn_1 ]
    properties:
      virtual_machine_interface_refs: [{ get_resource: vmi3 }]
      virtual_network_refs: [{ list_join: [':', { get_attr: [ child_vn_1, fq_name ] } ] }]

  vm3: 
    type: OS::Nova::Server 
    depends_on: [iip_3]
    properties: 
      name: { get_param: vmname3 } 
      image: { get_param: vmimage } 
      flavor: { get_param: vmflavor } 
      networks: 
        - port: { get_resource: vmi3 } 